### PR TITLE
Fix restart on Linux

### PR DESCRIPTION
**Pull request by ygcaicn**
Can't reproduce in local.
Test with Github workflow

### CODE REVIEW

**Comment by ygcaicn** [comment]
It's ok, but I don’t know the essential reason.

**Comment by ygcaicn** [comment]
It works fine with the exit function, but cannot use the return command. This seems to be a bug in qt. I wonder if we can consider a higher version of Qt?

**Comment by tamlok** [comment]
Thanks! I will merge your change to my PR.

Qt 5.15 is not a LTS version for open source community, right?

**Comment by ygcaicn** [comment]
> Thanks! I will merge your change to my PR.
> 
> Qt 5.15 is not a LTS version for open source community, right?

Yes.

**Pull request closed without merging**
